### ISSUE TITLE
Question About Training Process

### ISSUE THREAD

**Issue by QianSiWang1** [jianpengz/DoDNet#11]
Hello, thank you very much for the code you provided. I encountered some problems during training. During the training process, a dimensional abnormality error occurred at a certain epoch. What is the reason for this? 
torch.Size([1, 64, 32, 96, 96])
skip1 : shape torch.Size([1, 64, 32, 96, 95])
[32m16 22:01:46 [0m[1;31mWRN A exception occurred during Engine initialization, give up running process[0m
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 188, in main
    preds = model(images, task_ids)
  File "/home/test/anaconda3/envs/qy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/anaconda3/envs/qy/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/test/anaconda3/envs/qy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/qy/code/DoDNet/a_DynConv/unet3D_DynConv882.py", line 230, in forward
    x = x + skip1
RuntimeError: The size of tensor a (96) must match the size of tensor b (95) at non-singleton dimension 4

**Comment by QianSiWang1** [comment]
I think there may be a problem with some data and I need to find them out

**Comment by sherjy** [comment]
@Qy19970630  Hiiii, did you fix this problem?

**Comment by Qy19970630** [comment]
> @Qy19970630 Hiiii, did you fix this problem?

Yes，Just delete the wrong data

**Comment by QianSiWang1** [comment]
> @Qy19970630 Hiiii, did you fix this problem?

yes，Just delete the wrong data

**Comment by sherjy** [comment]
> > @Qy19970630 Hiiii, did you fix this problem?
> 
> yes，Just delete the wrong data

Thanks a lot! Will try.

**Comment by Huiimin5** [comment]
I think the problem is with skimage. I got a similar error on epoch 94 but the input images are all resized by skimage. So I downgrade scikit-image from 0.18 to 015. Now the training is at around epoch 200 and I don't see this error.

Btw, how many hours does it take to train the full MOTS dataset for 1000 epoch? It seems that I need >=5 days to finish the training. Is it normal?

**Comment by QianSiWang1** [comment]
> I think the problem is with skimage. I got a similar error on epoch 94 but the input images are all resized by skimage. So I downgrade scikit-image from 0.18 to 015. Now the training is at around epoch 200 and I don't see this error.
> 
> Btw, how many hours does it take to train the full MOTS dataset for 1000 epoch? It seems that I need >=5 days to finish the training. Is it normal?

Yes, it will take a lot of time
