### ISSUE TITLE
inconsistent data numbers on 2HepaticVessel 

### ISSUE THREAD

**Issue by Huiimin5** [jianpengz/DoDNet#12]
Hi, thank you a lot for your contribution.
I am trying to reproduce the results but find that on dataset 2Hippocampus, you have 242 + 61 = 303 images but in imagesTr folder under Task04_Hippocampus downloaded from MSD, I can only find 260 in total. How do you get labeled data from cases in imagesTs?

**Comment by jianpengz** [comment]
Hi @YolandaTheCoder , MOTS dataset doesn't cover Hippocampus. I guess you muddle up Hippocampus and HepaticVessel.

**Comment by Huiimin5** [comment]
Thank you so much for your response. That resolved my confusion.
