### ISSUE TITLE
Liver and Kidney Preprocessing

### ISSUE THREAD

**Issue by ShafinH** [jianpengz/DoDNet#15]
The [link](https://competitions.codalab.org/competitions/17094) that's given for the 0Liver data does not have the same format as the rest of the data with the `imagesTr/labelsTr/imagesTs` structure the rest of the datasets have. In the [`train.txt`](https://github.com/jianpengz/DoDNet/blob/main/dataset/list/MOTS/MOTS_train.txt) file, the 0Liver is given that structure. Where can I find the data for 0Liver that has this structuring?

Also, for the 1Kidney preprocessing, should line 28 on [`respacing.py`](https://github.com/jianpengz/DoDNet/blob/main/dataset/re_spacing.py) be `dirs1` and not `i_dirs1` so that the preprocessing for 1Kidey goes through this loop because the i_dirs1 is each specific case? Also, when going through this loop the data does not save in the spacing folder with `origin` as a sub folder. Is this an issue, or can I just delete the origin folder from the train.txt file?

**Comment by jianpengz** [comment]
Hi @ShafinH ,
As for the 0Liver dataset, you can access a standard format from [http://medicaldecathlon.com/](url). 
As for the 1Kidney datasets, "i_dirs1" in line 28 refers to the folder of the 1Kidney dataset. "dirs1" refers to the folders of all datasets. And the 1Kidney dataset was put in the "orginal/" folder in one old official version. If you don't have it, just create it and move the data to it, or delete the "origin/" in the list file.
