### ISSUE TITLE
cannot import name 'parse_devices' from 'utils.pyt_utils'

### ISSUE THREAD

**Issue by peterlv666** [jianpengz/DoDNet#3]
it's a great honor for me to read your paper, when i run your code i find  it shows 'cannot import name 'parse_devices' from 'utils.pyt_utils'', i checked the pyt_utils.py but didn't find the defination of parse_devices. i don't how to solve it ? thanks for your help.
![image](https://user-images.githubusercontent.com/75125316/113874847-c8ae3900-97e8-11eb-8197-cb3024fa33d9.png)

**Comment by jianpengz** [comment]
'parse_devices' should be deleted, and I have updated engine.py. Please try again!

**Comment by peterlv666** [comment]
@jianpengz  thanks for your help.

**Comment by TIAN-Ww** [comment]
Are you still running this program

**Comment by peterlv666** [comment]
yeah.The code can run,you need install related environment firstly.
