### ISSUE TITLE
How to directly run train.py ?

### ISSUE THREAD

**Issue by peterlv666** [jianpengz/DoDNet#5]
@jianpengz  i can run your code use your command in pycharm terminal ,but when i run the train.py directly it shows 'RuntimeError:' as the picture shows,can you tell me how to solve it ?thanks for your time and kindness.
![image](https://user-images.githubusercontent.com/75125316/114024195-5734c000-98a6-11eb-9dd7-b61f1d55b01e.png)
![image](https://user-images.githubusercontent.com/75125316/114024288-72073480-98a6-11eb-8cb7-fa1b70a7f8aa.png)

**Comment by jianpengz** [comment]
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=$RANDOM train.py \
--train_list='list/MOTS/MOTS_train.txt' \
--snapshot_dir='snapshots/dodnet' \
--input_size='64,192,192' \
--batch_size=2 \
--num_gpus=2 \
--num_epochs=1000 \
--start_epoch=0 \
--learning_rate=1e-2 \
--num_classes=2 \
--num_workers=8 \
--weight_std=True \
--random_mirror=True \
--random_scale=True \
--FP16=False

**Comment by jianpengz** [comment]
Please run train.py script as the following:

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=$RANDOM train.py \
--train_list='list/MOTS/MOTS_train.txt' \
--snapshot_dir='snapshots/dodnet' \
--input_size='64,192,192' \
--batch_size=2 \
--num_gpus=2 \
--num_epochs=1000 \
--start_epoch=0 \
--learning_rate=1e-2 \
--num_classes=2 \
--num_workers=8 \
--weight_std=True \
--random_mirror=True \
--random_scale=True \
--FP16=False
