### ISSUE TITLE
 KiTS19

### ISSUE THREAD

**Issue by ChiYe622** [jianpengz/DoDNet#6]
Hi, you really did an excelent job, and thanks for your sharing.
I have already prepared all datasets except KiTS19, other datasets work well on your code, they all got right results. I followed the steps in [KiTS19](https://github.com/neheller/kits19), but this result run by `evaluate.py` and `postp.py` is wrong. So, would you please tell me more details about how to get right KiTS19?
Thanks!

**Comment by jianpengz** [comment]
Did you re-space KiTS19 data by using the provided script re_spacing.py?

**Comment by ChiYe622** [comment]
Yes, I re-space all datasets including KiTS19, but only KiTS19 got wrong result.

**Comment by jianpengz** [comment]
I didn't have this issue before. Did you try with our pre-trained model or train it by yourself? Could the model fit the training samples on KiTS? I guess this problem was caused by the data.

**Comment by ChiYe622** [comment]
I used your pre-trained model, and I tried step by step two times, both failed. :-(

**Comment by jianpengz** [comment]
I tested KiTS using pre-trained model again and all cases work well during my testing. Here is a re-spaced case for test. Pls let me know whether it works in your environment. [example](https://drive.google.com/drive/folders/1C7Nva4KZoqPMLfgxawybSYaDrrMtuMGw?usp=sharing)

**Comment by ChiYe622** [comment]
I run your re-space case_00000 and my re-space case_00000 in the same environment, these are the results. I run case_00000 only.


`evaluate.py`
- Yours:
![jpevl](https://user-images.githubusercontent.com/44322425/116893691-daf28a00-ac63-11eb-8899-cc97d78fe08d.png)

- Mine:
![mine](https://user-images.githubusercontent.com/44322425/116894279-7257dd00-ac64-11eb-85cd-af2f49a0643d.jpg)


`post.py`

- Yours:
![jppp](https://user-images.githubusercontent.com/44322425/116894350-88fe3400-ac64-11eb-81a6-e3c5cdf5fa2d.png)

- Mine:
![mypp](https://user-images.githubusercontent.com/44322425/116894401-95828c80-ac64-11eb-80a9-4270fd3045d8.png)

**Comment by jianpengz** [comment]
Did you check is there a difference between two respacing cases?

**Comment by kangmintong** [comment]
> Hi, you really did an excelent job, and thanks for your sharing.
> I have already prepared all datasets except KiTS19, other datasets work well on your code, they all got right results. I followed the steps in [KiTS19](https://github.com/neheller/kits19), but this result run by `evaluate.py` and `postp.py` is wrong. So, would you please tell me more details about how to get right KiTS19?
> Thanks!

I got the same problem. Have you resolved the problem? Thanks.

**Comment by jianpengz** [comment]
Hi guys,
The pre-trained model was trained on the spacing of 3x0.76x0.76 for kits. To reproduce the results on kits, pls re-spacing the data to 3x0.76x0.76 and then test. Another pre-trained model trained on the spacing of 1.5x0.8x0.8 for kits would be released later.

**Comment by sherjy** [comment]
Hiii @ChiYe622 , did you met this problem? #11 , this problem occurs when I run codes on LiTS dataset only. I checked the image shapes after 'MOTSDataSet' processing, finding some image shapes becomes wrong, e.g. preset resize to (batch, channel, 64, 192, 192), but it'll happen to be a wrong shape (batch,channel,64,146,192) or other wrong shapes sometimes. I wonder if this problem comes from the data reason or sth else? Thanks in advance!
