### ISSUE TITLE
Question about metrics used in code.

### ISSUE THREAD

**Issue by hwei-cs** [jianpengz/DoDNet#7]
I noticed that when the number of nonzero voxels is zero, the hd95 is artificially set to  373.12866. Why choose it not other？

**Comment by jianpengz** [comment]
Thanks for the question. The HD95 value would be nan if there are no foregrounds in either the prediction or label. It was set to be ~373 following the BraTS challenge (math.sqrt(depth**2 + width**2 + height**2)), which is not exact but only a penalization item. Another alternative solution is ignoring the cases with nan HD95, which may lead to lower HD.

**Comment by hwei-cs** [comment]
Thank you for your kind reply, this helps me a lot, I will close this issue.
